{
 "title": "Portworx Cluster Dashboard Copy (no AM)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Cluster", "query": "px_cluster_cpu_percent" }
  ]
 },
 "panels": [
  {
   "title": "Portworx Cluster \"$Cluster\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Usage Meter",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(px_cluster_disk_utilized_bytes{cluster=~\"$Cluster\"})/sum(px_cluster_disk_total_bytes{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Capacity Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(px_cluster_disk_utilized_bytes{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Avg. Cluster CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(px_cluster_cpu_percent{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "# Nodes (total)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_cluster_size{cluster=~\"$Cluster\"}) "
    }
   ]
  },
  {
   "title": "Quorum",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_cluster_size{cluster=~\"$Cluster\"})/sum(px_cluster_status_cluster_quorum{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "# Nodes online",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_nodes_online{cluster=~\"$Cluster\"}) "
    }
   ]
  },
  {
   "title": "Storage Providers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_storage_nodes_online{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_cluster_size{cluster=\"$Cluster\"})-min(px_cluster_status_storage_nodes_online{cluster=\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Portworx Cluster \"$Cluster\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "Storage Pool Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    { "expr": "px_pool_stats_pool_status", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU utilization heat map",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "px_cluster_cpu_percent{cluster =~ \"$Cluster\"}"
    }
   ]
  },
  {
   "title": "Memory utilization heat map",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "px_cluster_memory_utilized_percent{cluster =~ \"$Cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}
{
 "title": "Portworx Node Dashboard (no AM)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Cluster", "query": "px_cluster_cpu_percent" },
   { "name": "Instances", "query": "px_cluster_cpu_percent" }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Members",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_cluster_size{cluster=~\"$Cluster\"}) "
    }
   ]
  },
  {
   "title": "Storage Providers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_storage_nodes_online{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "PWX Disk Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Cluster Disk Total",
     "expr": "px_cluster_disk_total_bytes{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_total_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Cluster Disk Used",
     "expr": "px_cluster_disk_utilized_bytes{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_utilized_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Instances \"$Instances\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU Usage: $tag_cluster - $tag_node",
     "expr": "px_cluster_cpu_percent{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_cpu_percent",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "PWX Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Memory Usage: $tag_node",
     "expr": "px_cluster_memory_utilized_percent{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_memory_utilized_percent",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Memory Usage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Network TX/RX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "IO Bytes TX",
     "expr": "px_network_io_bytessent{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bytes TX",
     "measurement": "px_network_io_bytessent",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "IO Bytes RX",
     "expr": "px_network_io_received_bytes{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bytes RX",
     "measurement": "px_network_io_received_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "PWX  Disk IO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "alias": "IO Pending",
     "expr": "irate(px_disk_stats_read_seconds {cluster=~\"$Cluster\",instance=~\"$Instances\"}[5m])",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Read {{cluster}} {{instance}}",
     "measurement": "px_cluster_pendingio",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "IO Pending",
     "expr": "irate(px_disk_stats_write_seconds {cluster=~\"$Cluster\",instance=~\"$Instances\"}[5m])",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Write  {{cluster}} {{instance}}",
     "measurement": "px_cluster_pendingio",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "PWX Disk throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Cluster Disk Total",
     "expr": "irate(px_disk_stats_read_bytes{cluster=~\"$Cluster\",instance=~\"$Instances\"}[5m])",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_total_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Cluster Disk Used",
     "expr": "irate(px_disk_stats_write_bytes{cluster=~\"$Cluster\",instance=~\"$Instances\"}[5m])",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_utilized_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "PWX Disk Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "alias": "Cluster Disk Total",
     "expr": "px_disk_stats_read_latency_seconds{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_total_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Cluster Disk Used",
     "expr": "px_disk_stats_write_latency_seconds{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_utilized_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  }
 ]
}
{
 "title": "PX Volume Info",
 "panels": [
  {
   "title": "Volume HA Level",
   "type": "table",
   "targets": [
    { "expr": "px_volume_halevel", "legendFormat": "{{volumename}}" }
   ]
  },
  {
   "title": "Volume Sizes",
   "type": "table",
   "targets": [
    { "expr": "px_volume_capacity_bytes", "legendFormat": "{{volumename}}" }
   ]
  },
  {
   "title": "Volume Usage Status",
   "type": "table",
   "targets": [
    {
     "expr": "(px_volume_usage_bytes/px_volume_capacity_bytes)*100",
     "legendFormat": "{{volumename}}"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Volume IO Depth",
   "type": "graph",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "px_volume_depth_io{volumeid=~\"$volumeid\"}",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "graph",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(px_volume_usage_bytes/px_volume_capacity_bytes)*100",
     "legendFormat": "{{volumename}}"
    }
   ]
  }
 ]
}
{
 "title": "Volume Latency Stats",
 "panels": [
  {
   "title": "Volume Read Latency",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "px_volume_vol_read_latency_seconds{volumeid=~\"$volumeid\"}",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Volume Write Latency",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "px_volume_vol_write_latency_seconds{volumeid=~\"$volumeid\"}",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Volume Utilization",
   "type": "graph",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(px_volume_iops{volumeid=~\"$volumeid\"}[5m])",
     "legendFormat": "{{volumename}}"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Volume IOPS",
   "type": "graph",
   "yaxes": [
    { "format": "short", "label": "IOPS" }
   ],
   "targets": [
    { "expr": "px_volume_iops", "legendFormat": "{{ volumename }}" }
   ]
  }
 ]
}
{
 "title": "Volume Throughput Stats",
 "panels": [
  {
   "title": "Volume Read Throughput",
   "type": "graph",
   "yaxes": [
    { "format": "bytes", "label": "Bytes/second" }
   ],
   "targets": [
    {
     "expr": "px_volume_readthroughput{volumeid=~\"$volumeid\"}",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Volume Write Throughput",
   "type": "graph",
   "yaxes": [
    { "format": "bytes", "label": "Bytes/second" }
   ],
   "targets": [
    {
     "expr": "px_volume_writethroughput{volumeid=~\"$volumeid\"} ",
     "legendFormat": "{{volumename}}"
    }
   ]
  }
 ]
}
{
 "title": "Disk Stats",
 "panels": [
  {
   "title": "Disk Read Rate",
   "type": "graph",
   "yaxes": [
    { "format": "short", "label": "Bytes per Second" }
   ],
   "targets": [
    {
     "expr": "irate( px_disk_stats_read_bytes[5m] )",
     "legendFormat": "{{ disk }} - {{ host }} "
    }
   ]
  },
  {
   "title": "Disk Write Rate",
   "type": "graph",
   "yaxes": [
    { "format": "short", "label": "Bytes per Second" }
   ],
   "targets": [
    {
     "expr": "irate( px_disk_stats_write_bytes[5m] )",
     "legendFormat": "{{ disk }} - {{ host }} "
    }
   ]
  }
 ]
}