apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: openshift-monitoring
  name: portworx-prometheus-sm
  labels:
    k8s-app: portworx
spec:
  selector:
    matchLabels:
      name: portworx
  namespaceSelector:
    matchNames:
    - kube-system
  endpoints:
  - port: px-api